AlertSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic.base import RedirectView,TemplateView
from AlertSystem import settings

urlpatterns = [
    path("user/",include("django.contrib.auth.urls") ),
    path('AlertApp/',include('Alert_App.urls'),name="AlertApp" ),
    path('admin/', admin.site.urls,name="admin"),
	path("",RedirectView.as_view(url="AlertApp/"),name="landing"),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Alert_App/urls.py
from django.urls import path
from django.views.generic.base import TemplateView, RedirectView
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib.auth.views import LoginView
from . import views
from Alert_App.models import Marker, DeviceId
app_name = "AlertApp" 


urlpatterns = [
	path('',TemplateView.as_view(template_name="home.html"),name="home"),
	
	path('login/',LoginView.as_view( template_name="registration/login.html",
	extra_context={'device_ids': [ marker.deviceid.id_number for marker in Marker.objects.all() ] }  ) , name="login_page"),
	
	#path('login/',views.login_page ,name="login_page"),
	path('index/',views.index,name="index"),
	path('report/',views.report,name="report"),
	path('map/',views.map,name="map"),
	path("response/",views.response,name="response"),
	path("sentReport/",views.sendReport,name="sendReport"),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

# Potential page travel: Home > Login > Index > Report > Map > Home

templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
	<title>{% block title %}Base Page{% endblock %}</title>
	{% load static %}
		<link rel="stylesheet" type="text/css" href="{% static 'Alert_App/css/style.css' %}">
    </head>
    <body>
        <main>
	    {% block content %}
	    {% endblock %}
	</main>
    </body>
</html>

templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Hawkeyed Rescue{% endblock %}

{% block content %}
<h1 id="main_msg">Home Page</h1>
	{% if user.is_authenticated %}
		<p style="color: black;">Hello, {{ user.username }}.</p>
		{% if user.is_superuser  %}
			<p><a href="{% url 'admin:index' %}">admin page</a></p>
			<p><a href="{% url 'AlertApp:index' %}">Go to reporting page.</a></p>
			<p><a href="{% url 'AlertApp:map' %}">Go to map page.</a></p>
		{% else %}
			<p><a href="{% url 'AlertApp:index' %}">Go to reporting page.</a></p>
		{% endif %}
		<p><a href="{% url 'logout' %}">logout</a></p>
	{% else %}
		<p style="color: black;">Must enter login credentials.</p>
		<a href="{% url 'AlertApp:login_page' %}">Login</a>
	{% endif %}
{% endblock %}