AlertSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic.base import RedirectView,TemplateView
from AlertSystem import settings

urlpatterns = [
    path("user/",include("django.contrib.auth.urls") ),
    path('AlertApp/',include('Alert_App.urls'),name="AlertApp" ),
    path('admin/', admin.site.urls,name="admin"),
	path("",RedirectView.as_view(url="AlertApp/"),name="landing"),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Alert_App/urls.py
from django.urls import path
from django.views.generic.base import TemplateView, RedirectView
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib.auth.views import LoginView
from . import views
from Alert_App.models import Marker, DeviceId
app_name = "AlertApp" 


urlpatterns = [
	path('',TemplateView.as_view(template_name="home.html"),name="home"),
	
	path('login/',LoginView.as_view( template_name="registration/login.html",
	extra_context={'device_ids': [ marker.deviceid.id_number for marker in Marker.objects.all() ] }  ) , name="login_page"),
	
	#path('login/',views.login_page ,name="login_page"),
	path('index/',views.index,name="index"),
	path('report/',views.report,name="report"),
	path('map/',views.map,name="map"),
	path("response/",views.response,name="response"),
	path("sentReport/",views.sendReport,name="sendReport"),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

# Potential page travel: Home > Login > Index > Report > Map > Home

Alert_App/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser, User
from django.dispatch import receiver


class Marker(models.Model):
	"""Defines a model for storing map markers that correspond to a location."""
	name = models.CharField(max_length=200,default="")
	x_position = models.FloatField(default=-1)
	y_position = models.FloatField(default=-1)
	activated = models.BooleanField(default=False)
	isAlerting = models.BooleanField(default=False)

	
class DeviceId(models.Model):
	"""Defines a model for storing device ids, which correspond with a Marker object."""
	marker = models.OneToOneField(Marker,on_delete=models.CASCADE)
	id_number = models.IntegerField(default=-1)
	
	
class Users(models.Model):
	"""Defines a model with custom attributes, which will be added to the base User class."""
	user = models.ForeignKey(User,on_delete=models.CASCADE)
	id = models.AutoField(primary_key=True)
	is_supervisor_user = models.BooleanField(default=False)
	using_device_number = models.IntegerField(default=-1)  #default is -1 to indicate that it hasn't been changed
	
	def get_supervisor_status(self):
		"""Returns status of whether a user is a supervisor or not."""
		return self.is_supervisor_user
	
	def get_is_authenticated(self):
		"""Returns authentication value."""
		return self.user.is_authenticated
		

def create_users(sender,instance,created,**kwargs):
	""" """
	if created:
		Users.objects.create(user=instance)

post_save.connect(create_users,sender=User,dispatch_uid="AlertApp.models")
#the post_save signal sends the model instance that needs to be saved

Alert_App/views.py
from django.contrib.auth import views as auth_views
from django.shortcuts import render
from django.contrib.auth import login
from django.contrib.auth import authenticate


from django.http import HttpResponse,HttpResponseRedirect
from django.http import Http404

from Alert_App.sendSms import sendAlertToPolice
from Alert_App.models import Marker, DeviceId
from AlertSystem import settings
import random 


def login_page(request):
	ids = []
	list_of_available_markers = Marker.objects.all()
	print(list_of_available_markers)
	for marker in list_of_available_markers:
		ids.append(marker.deviceid.id_number)
	context = {'device_ids':ids}
	return render(request,"registration\login.html",context)

	
def index(request):
	device_id = None
	user_type = None
	isNotValidUser = False
	users_obj = None
	msg = ""
	
	if request.method == "POST":
		username = request.POST.get('username',None)
		print(username)
		password = request.POST.get('password',None)
		print(password)
		
		if request.user.is_authenticated:
			pass #if user is already authenticated, skip 
		else:
				
			user = authenticate(username=username,password=password) #checks credentials against authentication backend
			
			if user:
				login(request,user) #if authenticated, login using database credentials
				device_id = request.POST.get('id_number',None)
				if device_id is not None:
					users_objs = request.user.users_set.filter(using_device_number__gt=-1)
					
					if len(users_objs) > 1:
						users_obj = users_objs[0] #only one users object should be attached to a user object
					elif len(users_objs) < 1:
						raise Exception("No users objects attached to user ")
					else:
						users_obj = users_objs[0]   # list -> single object
					
					users_obj.using_device_number = device_id
					print("stored device number as:"+users_obj.using_device_number)
					
				print(user)
				user_type = users_obj.is_supervisor_user #get user type for later use in forms
				print(user_type)
				users_obj.save()
				user.save()
			else:
				isNotValidUser = True #not a valid user
				msg = msg + "Not a valid user. "
	else:
		print("No post received")
		print(request.user)
		print(request.user.users_set.all())
		print(dir(request.user.users_set))
		users_objs = request.user.users_set.filter(using_device_number__gt=0)
		
		if len(users_objs) > 1:
			users_obj = users_objs[0] #only one users object should be attached to a user object
		elif len(users_objs) < 1:
			raise Exception("No users objects attached to user ")
		else:
			users_obj = users_objs[0]   # list -> single object
		
		device_id = users_obj.using_device_number
    
	list_of_available_markers = Marker.objects.all()
	
	isRegistered = False
	
	for marker in list_of_available_markers:
		if str(device_id) in str(marker.deviceid.id_number):
			isRegistered = True
			break 
	
	if (device_id == None) or (device_id == "" ) or (isRegistered is False):
		msg = msg + "Not using a registered device."
	else:
		msg = msg + "Logged in with device: " + str(device_id)
		
	context = {'message': msg,'user_type':user_type,'isNotValidUser':isNotValidUser,'users':users_obj}
	return render(request,'Alert_App/index.html', context)
	

def report(request):
	"""Sets up view for reporting emergencies."""
	user_type = None 
	if request.method == "POST":
		user_type = request.POST.get('user_type',None)
	context = {'user_type':user_type}
	return render(request,'Alert_App/report.html',context)
	

def map(request):
	"""Sets up view for map and markers."""
	Markers_list = Marker.objects.all() #stores all of the markers in a list
	marker_str = ""
	for marker in Markers_list:
		id = marker.deviceid.id_number
		x_pos = marker.x_position
		y_pos = marker.y_position
		isAlerting = marker.isAlerting
		
		marker_str = marker_str + f"{id} {x_pos} {y_pos} {isAlerting}|"
		print(marker_str)

	users_objs = request.user.users_set.filter(using_device_number__gt=-1)
					
	if len(users_objs) > 1:
		users_obj = users_objs[0] #only one users object should be attached to a user object
	elif len(users_objs) < 1:
		raise Exception("No users objects attached to user ")
	else:
		users_obj = users_objs[0]   # list -> single object
					
	isAllowed = users_obj.is_supervisor_user
	print(isAllowed)
	context = {'marker_str': marker_str,'isAllowed':isAllowed}
	
	return render(request,'Alert_App/map.html',context)
	
def response(request):
	"""Loads the response view to the report view submission."""
	report_type = None 
	if request.method == "POST":
		isShooter = request.POST.get('isSchoolShooting',None)
		isFire = request.POST.get('isFire',None)
		isInjury = request.POST.get('isInjury',None)
		
		if isShooter is not None:
			report_type = isShooter
		elif isFire is not None: 
			report_type = isFire
		elif isInjury is not None:
			report_type = isInjury
		else:
			report_type = None
	
	if report_type == None:
		return render(request,'Alert_App/response.html')
	elif report_type == "shooter":
		users_objs = request.user.users_set.filter(using_device_number__gt=0)
		
		if len(users_objs) > 1:
			users_obj = users_objs[0] #only one users object should be attached to a user object
		elif len(users_objs) < 1:
			raise Exception("No users objects attached to user ")
		else:
			users_obj = users_objs[0]   # list -> single object

		id_to_set = users_obj.using_device_number
		
		list_of_available_markers = Marker.objects.all()
		for marker in list_of_available_markers:
			if str(id_to_set) == str(marker.deviceid.id_number):
				marker.isAlerting = True
				marker.save()
		
		sendAlertToPolice(id_to_set)
		
	context = {'report_type':report_type}
	return render(request,'Alert_App/response.html',context)
	
	
def sendReport(request):
	"""Sends questionnaire results to officer too."""
	
	if request.method == "POST":
		shooter_proximity = request.POST.get('shooter_proximity',None)
		alone_or_group = request.POST.get('alone_or_group',None)
		any_injuries = request.POST.get('any_injuries',None)
		location_str = request.POST.get('location',None)
		
		if (shooter_proximity is None) and (alone_or_group is None) and (any_injuries is None) :
			print("No feedback.")
		else:
			msg_combination = f"Questionnaire for previous report: \n{shooter_proximity}\n{alone_or_group}\n{any_injuries}\n\n"
			if location_str is not None:
				print("Location is:"+location_str)
				msg_combination = msg_combination + location_str
		
			users_objs = request.user.users_set.filter(using_device_number__gte=0)
			
			if len(users_objs) > 1:
				users_obj = users_objs[0] #only one users object should be attached to a user object
			elif len(users_objs) < 1:
				raise Exception("No users objects attached to user ")
			else:
				users_obj = users_objs[0]   # list -> single object

			device_num = users_obj.using_device_number
			sendAlertToPolice(device_num,default_msg=msg_combination,addLocation=True )
		
	
	return render(request, 'home.html')
			

Alert_App/templates/Alert_App/AlertAppBase.html
<!DOCTYPE html>
<html lang="eng">
	<head>
		<meta charset="utf-8">
		{% load static %}
		<link rel="stylesheet" type="text/css" href="{% static 'Alert_App/css/style.css' %}">
		<script type="text/javascript" src="{% static 'Alert_App/go_back.js' %}"></script>
		<script type="text/javascript" src="{% static 'Alert_App/getLocation.js' %}"></script>
		<title>{%  block title %}Hawkeyed Rescue{% endblock %}</title>
	</head>

	<body>
		{% block content %}{% endblock %}
	</body>
</html>

Alert_App/templates/Alert_App/index.html
{% extends "Alert_App/AlertAppBase.html" %}

{%  block title %}Hawkeyed Rescue{% endblock%}

{% block content %}
	<h1>Hawkeyed Rescue</h1>
	{% csrf_token %}
	
	{% if users.is_supervisor_user %}
		<p style="color: black;">Supervisor user has logged in.</p>
	{% endif %}
	
	{% if isNotValidUser %}
		<p style="color: red;">Not a valid user.</p>
	{% else %}
		{% if message %}
		<!-- Can access passed dictionary values w/ bracket syntax -->
				<p style="color: black;">{{ message }}</p>
		{% endif %}
		<form method="post" action="{% url 'AlertApp:report' %}">
		{% csrf_token %}
			<button type="submit">Report Emergency</button>
			<input type="hidden" name="user_type" value={{ user_type }}>
		</form>
		{% if user.is_superuser  %}
			<a href="{% url 'AlertApp:home' %}">Go to Home page</a>
		{% endif %}
	{% endif %}
	
{% endblock %}

Alert_App/templates/Alert_App/map.html
{% extends "Alert_App/AlertAppBase.html" %}

{%  block title %}Hawkeyed Rescue{% endblock%}

{% block content %}
	<h1>Building Map</h1>
	{% load static %}
	<img src="{%  static "Alert_App/images/school_map_example.jpg" %}"
	alt="Example of floor plan" style="width:500px;height:500px;display: none;" id="map" ><br>
	
	{% if isAllowed == True  %}
		<input type="hidden" name="markers" id="data_store" value="{{ marker_str }}" />
		<!--"Markers" hidden element stores marker information in this format:
		<device_id x_position y_position isAlerting|>                              -->
		
		<button type="button" onClick="allowEdits()" id="edit_button" style="display:none;">Edit Registered Device Locations</button>
		<!--edit button is hidden because editing will be done in the admin page instead  -->
		<p align="center">
			<canvas id="Canvas" height="600" width="600" align="right"></canvas>
		</p>
		
		<script>
			window.onload = showMarkers;
			function showMarkers(){
				var map = document.getElementById("map");
				var canvas = document.getElementById("Canvas");
				
				var data_store = document.getElementById("data_store");
				var markers_string = data_store.value;  //this string contains information about the available markers
				
				// begin making markers 
				var context = canvas.getContext("2d")
				var mapSprite = new Image();
				mapSprite.src = map.src;
				
				var Marker = function () {
					this.Sprite = new Image();
					this.Sprite.src = "http://www.clker.com/cliparts/w/O/e/P/x/i/map-marker-hi.png"
					this.alert_sprite_src = "http://www.clker.com/cliparts/j/4/f/Y/g/Q/orange-pin-th.png" //sprite shown if isAlerting is true
					this.Width = 12;
					this.Height = 20;
					this.XPos = 0;
					this.YPos = 0;
					this.id = "";
					//this.isAlerting = ""; //empty strings are false when evaluated with Boolean()
				}

				// Array of markers
				var Markers = new Array();
				
				// Format of data: "1 100 100|2 200 200"
				var marker_list = markers_string.split("|");
				var len = marker_list.length;
				
				for(i=0;i<len;i++){
					var substring = marker_list[i];
					var data = substring.split(" ");
					
					var marker = new Marker();
					marker.id = data[0];
					marker.XPos = data[1];
					marker.YPos = data[2];
					
					if (data[3] == "True") { 
						//marker.isAlerting = data[3];
						marker.Sprite.src = marker.alert_sprite_src;
					}
					//default of empty string is kept if not true, which will evaluate to false
					Markers.push(marker);
				}
				
				var main = function () {
					// Update our canvas
					draw();
				};
				
				var draw = function () {
					// Clear Canvas
					context.fillStyle = "#000";
					context.fillRect(0, 0, canvas.width, canvas.height);
					context.drawImage(mapSprite, 0, 0,canvas.width,canvas.height);
					context.font = context.font.replace(/\d+px/, "15px");
					// Draw markers
					for (var i = 0; i < Markers.length; i++) {
						var tempMarker = Markers[i];

						context.drawImage(tempMarker.Sprite, tempMarker.XPos, tempMarker.YPos, tempMarker.Width, tempMarker.Height);
						// Calculate position text
						var markerText = "Device #" + (i +1); //+ " Position (X:" + tempMarker.XPos + ", Y:" + tempMarker.YPos + ")";
						
						// Draw a simple box so you can see the position
						var textMeasurements = context.measureText(markerText);
						context.fillStyle = "#666";
						context.globalAlpha = 0.7;
						context.fillRect(tempMarker.XPos - (textMeasurements.width / 2), tempMarker.YPos - 15, textMeasurements.width, 20);
						context.globalAlpha = 1;

						// Draw position above
						context.fillStyle = "#F80606";
						context.fillText(markerText, tempMarker.XPos, tempMarker.YPos);
						context.textBaseline = "middle";
						context.textAlign = "center";
						
					}
					
				}
				setInterval(main, (1000 / 60)); // Refresh 60 times a second
			}
			
			function cancelEdit(){
				//resets page to initial elements and layout
				//var map = document.getElementById("map");
				//map.style.display = ""; //revert to original display
				
				var edit_button = document.getElementById("edit_button");
				edit_button.style.display = "";
				
				//var canvas = document.getElementById("Canvas");
				//canvas.style.display = "none";  //revert to original display
				
				var tmp = document.getElementById("cancel_button");
				tmp.style.display = "none";
				tmp.parentNode.removeChild(tmp)
				
				showMarkers();
			}
			function allowEdits(){
				//displays canvas for adding new devices
				var map = document.getElementById("map");
				//map.style.display = "none";
				
				var edit_button = document.getElementById("edit_button");
				edit_button.style.display = "none";

				var canvas = document.getElementById("Canvas");
				canvas.style.display = "block";
				
				var data_store = document.getElementById("data_store");
				
				//creates a cancel button 
				var btn = document.createElement("BUTTON");
				btn.setAttribute("id", "cancel_button");
				btn.onclick = cancelEdit;
				var text_str = document.createTextNode("Cancel?");
				btn.appendChild(text_str);
				document.body.appendChild(btn);
				
				// begin making markers 
				var context = canvas.getContext("2d")
				var mapSprite = new Image();
				mapSprite.src = map.src;
				
				var Marker = function () {
					this.Sprite = new Image();
					this.Sprite.src = "http://www.clker.com/cliparts/w/O/e/P/x/i/map-marker-hi.png"
					this.Width = 12;
					this.Height = 20;
					this.XPos = 0;
					this.YPos = 0;
				}

				// Array of markers
				var Markers = new Array();

				// When the user clicks their mouse on our canvas run this code
				var mouseClicked = function (mouse) {
					// Get corrent mouse coords
					var rect = canvas.getBoundingClientRect();
					var mouseXPos = (mouse.x - rect.left);
					var mouseYPos = (mouse.y - rect.top);

					// Move the marker when placed to a better location
					var marker = new Marker();
					marker.XPos = mouseXPos - (marker.Width / 2);
					marker.YPos = mouseYPos - marker.Height;

					// Push our new marker to our Markers array
					Markers.push(marker);
				}

				// Add mouse click event listener to canvas
				canvas.addEventListener("mousedown", mouseClicked, false);

				// Run this once so we setup text rendering
				var firstLoad = function () {
					context.font = "15px Georgia";
					context.textAlign = "center";
				}

				firstLoad();

				// This will be called 60 times a second, look at the code at the bottom `setInterval`
				var main = function () {
					// Update our canvas
					draw();
				};

				var draw = function () {
					// Clear Canvas
					context.fillStyle = "#000";
					context.fillRect(0, 0, canvas.width, canvas.height);

					// Draw map
					// Sprite, X location, Y location, Image width, Image height
					// You can leave the image height and width off, if you do it will draw the image at default size
					context.drawImage(mapSprite, 0, 0,canvas.width,canvas.height);
					
					var data_builder = "";
					// Draw markers
					for (var i = 0; i < Markers.length; i++) {
						
						var tempMarker = Markers[i];
						// Draw marker
						context.drawImage(tempMarker.Sprite, tempMarker.XPos, tempMarker.YPos, tempMarker.Width, tempMarker.Height);
						data_builder += "<"+ (i+1).toString() + ","+(tempMarker.XPos).toString()+ ","+tempMarker.YPos.toString() +">";
						data_store.value = data_builder;
						// Calculate position text
						var markerText = "Device #" + (i +1); //+ " Position (X:" + tempMarker.XPos + ", Y:" + tempMarker.YPos + ")";
						
						// Draw a simple box so you can see the position
						var textMeasurements = context.measureText(markerText);
						context.fillStyle = "#666";
						context.globalAlpha = 0.7;
						context.fillRect(tempMarker.XPos - (textMeasurements.width / 2), tempMarker.YPos - 15, textMeasurements.width, 20);
						context.globalAlpha = 1;

						// Draw position above
						context.fillStyle = "#F83106";
						context.fillText(markerText, tempMarker.XPos, tempMarker.YPos);
					}
				};
				setInterval(main, (1000 / 60)); // Refresh 60 times a second
			} 
			
			
		</script>
	{% endif %}
	<button onclick="go_back()">Go Back</button>
	
{% endblock%}

Alert_App/templates/Alert_App/report.html
{% extends "Alert_App/AlertAppBase.html" %}

{%  block title %}Hawkeyed Rescue{% endblock%}



{% block content %}
	<h1>Hawkeyed Report Page</h1>
	{% if user_type %}
		<form method="post" action="{% url 'AlertApp:map' %}">
		{% csrf_token %}
			<button type="submit">Reportings Map</button>
		</form>
	{% endif %}
	<p>
		<form method="post" action="{% url 'AlertApp:response' %}">
		{% csrf_token %}
			<button type="submit">School shooting!</button>
			<input type="hidden" name="isSchoolShooting" value="shooter">
		</form>
	</p>
	<p>
		<form method="post" action="{% url 'AlertApp:response' %}">
		{% csrf_token %}
			<button type="submit">Fire!</button>
			<input type="hidden" name="isFire" value="fire">
		</form>
	</p>
	<p>
		<form method="post" action="{% url 'AlertApp:response' %}">
		{% csrf_token %}
			<button type="submit">Injury!</button>
			<input type="hidden" name="isInjury" value="injury">
		</form>
	</p>
	<form method="post" action="{% url 'logout' %}">
	{% csrf_token %}
		<button type="submit">Finish</button>
	</form>
{% endblock %}

Alert_App/templates/Alert_App/response.html
{% extends "Alert_App/AlertAppBase.html" %}

{%  block title %}Hawkeyed Rescue{% endblock%}



{% block content %}
	<h1>Extended Response Page</h1>
	<input type="hidden" name="location" value="5" form="question_form" id="location_id">
	<script>
		var x = document.getElementById("location_id");
		getLocation()
	</script>
	{% if report_type  %} 
		<p style="color: black;">{{ report_type|upper }} REPORT has been sent. Stay calm and please wait for proper authority.</p>
		
		{%  if report_type == "shooter" %}
			<form method="post" action="{% url 'AlertApp:sendReport' %}" id="question_form">
			{% csrf_token %}
				<p id="questionnaire">Please fill out the questionnaire.</p>
				
				<p id="questionnaire">Is the shooter near you?</p>
				<select name="shooter_proximity" id="questionnaire" style="color: black;">
					<option value="The shooter is near me." id="questionnaire">The shooter is near me.</option>
					<option value="The shooter is not near me." id="questionnaire">The shooter is not near me.</option>
				</select>
				
				<p id="questionnaire">Are you with other people?</p>
				<select name="alone_or_group">
					<option value="I am alone." id="questionnaire">I am alone</option>
					<option value="I am with other people." id="questionnaire">I am with other people.</option>
				</select>
				
				<p id="questionnaire">Are there any injured people around you?</p>
				<select name="any_injuries">
					<option value="No injuries." id="questionnaire">No injuries.</option>
					<option value="1 person injured." id="questionnaire">1 person is injured.</option>
					<option value="Multiple people are injured." id="questionnaire">Multiple people are injured.</option>
				</select>
				
				<input type="submit">
			</form>
		{% endif%}
		
		<p><a href="{% url 'logout' %}">logout</a></p>
	{% else %}
		<p>No report was submitted.</p>
		<button onclick="go_back()">Go Back</button>
	{% endif %}
{% endblock %}